### ISSUE TITLE
请问如何获得直播间信息页的url？

### ISSUE THREAD

**Issue by luwi2001** [LyzenX/DouyinLiveRecorder#20]
就是dy_api里get_api_url(room_id)里返回的url，我翻遍网页源代码也没找到
如果有空能解答一下感激不尽

**Comment by LyzenX** [comment]
是通过抓包获取的，不在网页源代码里。
具体做法：
1. 使用一个可以抓包的浏览器(Chorme、Edge等大多数主流浏览器都有)
2. 进入一个**正在**直播的直播间网页(在 http://live.douyin.com 随便找一个就行)
3. 打开*开发者选项*(大多默认是按键盘上的`F12`按键)
4. 在弹出的窗口中点击`网络`(或`Network`)
5. 刷新网页(重新开始抓包)
6. 寻找可能的对象(可以筛选掉css、js、png等明显无关文件)
7. 找到一个可疑的包，链接是`https://live.douyin.com/webcast/room/web/enter/....`，点开它
8. 点击`响应`(Response)、`预览`(Preview)等，看到这个包的响应中有关键内容，故重点研究这个包

**Comment by luwi2001** [comment]
非常感谢！
