### ISSUE TITLE
抖音弹幕的问题有人说是因为这个

### ISSUE THREAD

**Issue by ChooseBetterr** [LyzenX/DouyinLiveRecorder#49]
https://github.com/biliup/biliup/issues/965

**Comment by LyzenX** [comment]
是因为接口更新了需要signature参数导致的，目前最大的难点在于自动计算或获取signature

**Comment by LyzenX** [comment]
好像少提交了一个文件，clone一下最新版本或者把dylr/core/dy_protocol.py改名为dy_pb2.py
